# Generated by Django 4.1.3 on 2022-11-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_bills_code_alter_clients_type_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='nit',
            field=models.PositiveBigIntegerField(verbose_name='NIT'),
        ),
    ]
